#pragma once
#ifndef PPM_IMAGE_HPP
#define PPM_IMAGE_HPP
#include "image.hpp"
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <vector>

class PPMImage : public Image
{
public:
	PPMImage(size_t rows, size_t cols) : Image(rows, cols) {}

	bool load(const std::string &filePath) override
	{
		std::ifstream file(filePath);
		if (!file.is_open()) return false;

		std::string line, format;
		std::getline(file, format);
		format.erase(format.find_last_not_of(" \t\r\n") + 1);
		if (format != "P3") return false;

		while (std::getline(file, line))
		{
			if (line[0] != '#') break;
		}

		std::istringstream dimensions(line);
		dimensions >> cols >> rows;

		int maxVal;
		file >> maxVal;

		pixels.resize(rows * cols * 3);
		for (size_t i = 0; i < rows * cols * 3; ++i)
		{
			if (!(file >> pixels[i])) return false;
		}

		return true;
	}

	void save(const std::string &filePath) const override
	{
		std::ofstream file(filePath);
		if (!file.is_open()) throw std::runtime_error("Unable to open file");

		file << "P3\n";
		file << "# Generated by Image class\n";
		file << cols << " " << rows << "\n255\n";

		for (size_t i = 0; i < rows; ++i)
		{
			for (size_t j = 0; j < cols; ++j)
			{
				file << pixels[(i * cols + j) * 3] << " "
					<< pixels[(i * cols + j) * 3 + 1] << " "
					<< pixels[(i * cols + j) * 3 + 2] << " ";
			}
			file << "\n";
		}
	}
};
#endif // PPM_IMAGE_HPP
